"""add vendor_name to documents

Revision ID: 706d6c58c468
Revises: ba9366efd6d2
Create Date: 2026-08-04 21:02:13.560185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '706d6c58c468'
down_revision: Union[str, Sequence[str], None] = 'ba9366efd6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.add_column('documents', sa.Column('vendor_name', sa.String(), nullable=True))
    op.alter_column('results', 'feature_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'feature_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('documents', 'vendor_name')
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('view_mode', sa.TEXT(), server_default=sa.text("'simple'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('user_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_preferences_pkey'))
    )
    # ### end Alembic commands ###
