"""phase5_add_columns

Revision ID: ba9366efd6d2
Revises: 44309c0dbbab
Create Date: 2026-07-06 15:42:27.253801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9366efd6d2'
down_revision: Union[str, Sequence[str], None] = '44309c0dbbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('plain_language', sa.JSON(), nullable=True))
    op.add_column('results', sa.Column('timeline_events', sa.JSON(), nullable=True))
    op.add_column('results', sa.Column('recommendation', sa.JSON(), nullable=True))
    op.add_column('results', sa.Column('insight', sa.JSON(), nullable=True))
    op.add_column('results', sa.Column('red_team', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'red_team')
    op.drop_column('results', 'insight')
    op.drop_column('results', 'recommendation')
    op.drop_column('results', 'timeline_events')
    op.drop_column('results', 'plain_language')
    # ### end Alembic commands ###
