"""add tour_seen to profiles

Revision ID: c68221d27e33
Revises: 706d6c58c468
Create Date: 2026-08-07 17:08:12.420493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68221d27e33'
down_revision: Union[str, Sequence[str], None] = '706d6c58c468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('tour_seen', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'tour_seen')
    # ### end Alembic commands ###
